#############################################################################
# Makefile for building: auv
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Mar 9 04:25:16 2018
# Project:  auv.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile auv.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		signalsfromcpp.cpp moc_main.cpp \
		moc_integrateros.cpp \
		qrc_qml.cpp
OBJECTS       = main.o \
		signalsfromcpp.o \
		moc_main.o \
		moc_integrateros.o \
		qrc_qml.o
DIST          = welcome.qml \
		tab2.qml \
		sensor_name.qml \
		sensor_topics.qml \
		sensor_stats.qml \
		monitor.qml \
		nodes.qml \
		node_des1.qml \
		reconfig.qml \
		alpha.qml \
		remote.qml \
		build/Alpha3 \
		auv \
		down.png \
		logo \
		.png \
		up.png \
		README.md \
		logo \
		.png \
		Remote/remote_sway.qml \
		Remote/remote_vrward.qml \
		Remote/remote_forward.qml \
		logo \
		.png \
		remote/remote_forward.qml \
		remote/remote_sway.qml \
		remote/remote_vrward.qml \
		remote/remote_sway.qml.autosave \
		../../../../../opt/ros/kinetic/bin/binvox2bt \
		../../../../../opt/ros/kinetic/bin/bt2vrml \
		../../../../../opt/ros/kinetic/bin/compare_octrees \
		../../../../../opt/ros/kinetic/bin/convert_octree \
		../../../../../opt/ros/kinetic/bin/edit_octree \
		../../../../../opt/ros/kinetic/bin/eval_octree_accuracy \
		../../../../../opt/ros/kinetic/bin/graph2tree \
		../../../../../opt/ros/kinetic/bin/log2graph \
		../../../../../opt/ros/kinetic/bin/opencv_annotation \
		../../../../../opt/ros/kinetic/bin/opencv_createsamples \
		../../../../../opt/ros/kinetic/bin/opencv_interactive-calibration \
		../../../../../opt/ros/kinetic/bin/opencv_traincascade \
		../../../../../opt/ros/kinetic/bin/opencv_version \
		../../../../../opt/ros/kinetic/bin/opencv_visualisation \
		../../../../../opt/ros/kinetic/bin/opencv_waldboost_detector \
		../../../../../opt/ros/kinetic/bin/rospack \
		../../../../../opt/ros/kinetic/bin/rosstack \
		../../../../../opt/ros/kinetic/bin/run_selftest \
		../../../../../opt/ros/kinetic/bin/rviz \
		../../../../../opt/ros/kinetic/bin/selftest_example \
		../../../../../opt/ros/kinetic/bin/selftest_rostest \
		../../../../../opt/ros/kinetic/bin/stage \
		../../../../../opt/ros/kinetic/bin/rosrun \
		../../../../../opt/ros/kinetic/bin/tf_remap \
		../../../../../opt/ros/kinetic/bin/view_frames \
		../../../../../opt/ros/kinetic/bin/catkin_create_qt_pkg \
		../../../../../opt/ros/kinetic/bin/catkin_find \
		../../../../../opt/ros/kinetic/bin/catkin_init_workspace \
		../../../../../opt/ros/kinetic/bin/catkin_make \
		../../../../../opt/ros/kinetic/bin/catkin_make_isolated \
		../../../../../opt/ros/kinetic/bin/catkin_package_version \
		../../../../../opt/ros/kinetic/bin/catkin_prepare_release \
		../../../../../opt/ros/kinetic/bin/catkin_test_results \
		../../../../../opt/ros/kinetic/bin/catkin_topological_order \
		../../../../../opt/ros/kinetic/bin/rosbag \
		../../../../../opt/ros/kinetic/bin/rosboost-cfg \
		../../../../../opt/ros/kinetic/bin/rosclean \
		../../../../../opt/ros/kinetic/bin/rosconsole \
		../../../../../opt/ros/kinetic/bin/roscore \
		../../../../../opt/ros/kinetic/bin/roscreate-pkg \
		../../../../../opt/ros/kinetic/bin/rosgraph \
		../../../../../opt/ros/kinetic/bin/roslaunch \
		../../../../../opt/ros/kinetic/bin/roslaunch-complete \
		../../../../../opt/ros/kinetic/bin/roslaunch-deps \
		../../../../../opt/ros/kinetic/bin/roslaunch-logs \
		../../../../../opt/ros/kinetic/bin/rosmake \
		../../../../../opt/ros/kinetic/bin/rosmaster \
		../../../../../opt/ros/kinetic/bin/rosmsg \
		../../../../../opt/ros/kinetic/bin/rosmsg-proto \
		../../../../../opt/ros/kinetic/bin/rosnode \
		../../../../../opt/ros/kinetic/bin/rosparam \
		../../../../../opt/ros/kinetic/bin/rosservice \
		../../../../../opt/ros/kinetic/bin/rossrv \
		../../../../../opt/ros/kinetic/bin/rostest \
		../../../../../opt/ros/kinetic/bin/rostopic \
		../../../../../opt/ros/kinetic/bin/rosunit \
		../../../../../opt/ros/kinetic/bin/roswtf \
		../../../../../opt/ros/kinetic/bin/rqt \
		../../../../../opt/ros/kinetic/bin/rqt_bag \
		../../../../../opt/ros/kinetic/bin/rqt_console \
		../../../../../opt/ros/kinetic/bin/rqt_dep \
		../../../../../opt/ros/kinetic/bin/rqt_graph \
		../../../../../opt/ros/kinetic/bin/rqt_image_view \
		../../../../../opt/ros/kinetic/bin/rqt_logger_level \
		../../../../../opt/ros/kinetic/bin/rqt_plot \
		../../../../../opt/ros/kinetic/bin/rqt_shell \
		../../../../../opt/ros/kinetic/bin/xacro \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3drender.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_designer.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_help.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_help_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_nfc.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_script.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_script_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scxml.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialport.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_uitools.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webengine.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_websockets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webview.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/exceptions.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		auv.pro
QMAKE_TARGET  = auv
DESTDIR       = 
TARGET        = auv

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: auv.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3drender.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_core_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_designer.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_help.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_help_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_location_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_network_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_nfc.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_script.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_script_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scxml.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialport.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_uitools.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webengine.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_websockets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webview.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt4/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		deployment.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/exceptions.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile auv.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dcore.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dextras.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dinput.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquick.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3drender.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_core_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_designer.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_designer_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_gamepad.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_gui_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_help.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_help_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_location.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_location_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_multimedia.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_network_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_nfc.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_positioning.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_printsupport.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_purchasing.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_qml_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_qmltest.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quick_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_script.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_script_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_scripttools.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_scxml.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_sensors.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_serialbus.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_serialport.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_sql_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_svg.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_svg_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_testlib.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_uitools.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webchannel.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webengine.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_websockets.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webview.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_webview_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_x11extras.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_xml_private.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/share/qt4/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
deployment.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/exceptions.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile auv.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/auv1.0.0 || $(MKDIR) .tmp/auv1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/auv1.0.0/ && $(COPY_FILE) --parents main.h signalsfromcpp.h integrateros.h .tmp/auv1.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/auv1.0.0/ && $(COPY_FILE) --parents main.cpp signalsfromcpp.cpp .tmp/auv1.0.0/ && (cd `dirname .tmp/auv1.0.0` && $(TAR) auv1.0.0.tar auv1.0.0 && $(COMPRESS) auv1.0.0.tar) && $(MOVE) `dirname .tmp/auv1.0.0`/auv1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/auv1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_main.cpp moc_integrateros.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp moc_integrateros.cpp
moc_main.cpp: main.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) main.h -o moc_main.cpp

moc_integrateros.cpp: integrateros.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) integrateros.h -o moc_integrateros.cpp

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		welcome.qml \
		MainForm.ui.qml \
		monitor.qml \
		down.png \
		data_log.qml \
		up.png \
		reconfig.qml \
		sensor_name.qml \
		sensors.qml \
		node_des1.qml \
		sensor_stats.qml \
		main.qml \
		snippets.qml \
		nodes.qml \
		sensor_topics.qml \
		remote.qml \
		remote/thrust2.qml \
		remote/remote_sway.qml \
		remote/thrust4.qml \
		remote/thrust3.qml \
		remote/thrust5.qml \
		remote/anticlock.png \
		remote/thrust1.qml \
		remote/clock.png \
		remote/remote_upward.qml \
		remote/thrust6.qml \
		remote/remote_forward.qml
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp main.h \
		integrateros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

signalsfromcpp.o: signalsfromcpp.cpp signalsfromcpp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalsfromcpp.o signalsfromcpp.cpp

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

moc_integrateros.o: moc_integrateros.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_integrateros.o moc_integrateros.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/auv/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/auv/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/auv/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/auv/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/auv/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/auv/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

