yaw:
  p: -3.5
  i: 0
  d: -0.2
  band: 1

roll:
  p: -3.5
  i: 0
  d: -0.2
  band: 1

pitch:
  p: -3.5
  i: 0
  d: -0.2
  band: 1

heave:
  p: -1.5
  i: 0
  d: 0
  band: 4

surge:
  p: 3.75
  i: 0
  d: 0
  band: 10

sway:
  p: 1.1
  i: 0
  d: 1
  band: 15
